[DCE-156] Dotnet Web Application Walking Skeleton
DBeniskos/practice-basic-webapi-application pull request #1
Opened 2024-01-17 13:06 UTC by DBeniskos

Create scaffolding for dotnet application

2024-01-17 13:12 UTC, sethpthomas91 commented
Can you please add a README with instructions how to run this app?

2024-01-17 15:41 UTC, DBeniskos commented
I have updated the README file

2024-01-17 22:21 UTC, sethpthomas91 commented on README.md
Let's make this even more user friendly. Assume your uer has no idea what requirements your software needs. Think in things like dotnet version. Also let's look at using code snippets in Github markdown.

Some README sources: 
- https://www.makeareadme.com/
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

When I was learning Ruby a few years ago I loved guard's [README](https://github.com/guard/guard#installation)

2024-01-18 07:57 UTC, DBeniskos commented on README.md
Ok Im gonna give more instructions

2024-01-18 10:21 UTC, DBeniskos commented on README.md
I added more instructions in Readme file. Please have a look.

2024-01-18 13:07 UTC, sethpthomas91 commented on README.md
In the future please re-request the review on the top right of the conversation page! Thanks!

2024-01-18 13:20 UTC, sethpthomas91 requested changes

2024-01-18 13:20 UTC, sethpthomas91 commented on README.md
> +- .NET Install Tool
```suggestion
```

2024-01-18 13:20 UTC, sethpthomas91 commented on README.md
> +- .NET Install Tool
Good info, but a bit too much. This assumes that folks are using the linux distro. Maybe just scrap this.

2024-01-18 13:20 UTC, sethpthomas91 commented on README.md
> +- in terminal run ```dotnet build``` in order to run this application
`dotnet build` will not give you the "Hello world" output. `dotnet build` only builds the application, but does not run it. `dotnet run --project src/ ` will run the application, but you have to first run a `dotnet build` command beforehand.

2024-01-18 13:28 UTC, sethpthomas91 commented
Also take a look at the JIRA story and get the rest of this story done please!

2024-01-19 09:30 UTC, DBeniskos commented
I have completed the Dotnet Web Application Initial PR pt1

2024-01-19 13:11 UTC, sethpthomas91 requested changes

2024-01-19 13:11 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +        run: dotnet build ./src/WebApi.csproj
```suggestion
```

2024-01-19 13:11 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +          path: /home/runner/work/Artifacts/release/
```suggestion
```
out of scope

2024-01-19 13:11 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +          path: /home/runner/work/Artifacts/release/
```suggestion
```
out of scope

2024-01-19 13:11 UTC, sethpthomas91 commented on test/UnitTest1.cs
> +namespace test;
The tests were not included as part of DCE-156.

2024-01-19 13:59 UTC, sethpthomas91 requested changes
Good job. Minor changes requested. Please ask if you have any questions.

2024-01-19 13:59 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +      - feature/DCE-156-walking-skeleton
```suggestion
```

2024-01-19 13:59 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +      - feature/DCE-156-walking-skeleton
We could also look into doing a workflow dispatch in the future, but it is not required now.

2024-01-19 13:59 UTC, sethpthomas91 commented on README.md
> +- after that run ```dotnet run --project src/``` to run the application
Need instructions to shut down. Also Hello world does not display to terminal. It opens up the web api prompt.

2024-01-19 14:35 UTC, sethpthomas91 approved these changes
Great job

2024-01-19 14:40 UTC, merged