Feature/dce 163 add testing
DBeniskos/practice-basic-webapi-application pull request #4
Opened 2024-01-22 12:47 UTC by DBeniskos

In this pull request i added a simple example of xunit testing in dotnet.
Also i updated the Instructions in Readme file on how to run this unit test if you are a ubuntu user.

2024-01-22 13:14 UTC, sethpthomas91 requested changes
Take a look at the Microsoft dotnet docs on how testing projects are named. Can you fix this to look like any of the example projects they offer? Ususally the csproj is not just called test.csproj and reflects the project it is testing.

2024-01-23 11:49 UTC, SergiiVolodkoWorking commented on README.md
> +- in terminal run the following comand :
Will it work if someone just clone the project and execute `dotnet test` from it? Aren't we lacking some more details in these instructions?

2024-01-23 11:49 UTC, SergiiVolodkoWorking commented on test/UnitTest1.cs
> +
Could you please add a trivial assertion here? So the test is not empty and we have a way to see that the tests can fail if the assertion is false.

2024-01-23 11:50 UTC, SergiiVolodkoWorking commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
👍

2024-01-23 11:56 UTC, SergiiVolodkoWorking commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
Good understanding of C# projects. Just be cautious that even for single WebApi project, we might need multiple testing projects: WebApi.IntegrationTests, WebApi.E2ETest, WebApi.Tests (for unit testing).
So for this task current structure will work, but for Portal backend it won't suit.

2024-01-23 13:46 UTC, DBeniskos commented on .github/pull_request_template.md
> +
I resolved the conflict about PrTemplate, so this change in the PrTemplate is not existing anymore.

2024-01-23 13:51 UTC, DBeniskos commented on README.md
> +- in terminal run the following comand :
So i have to add this i guess just like the step Buld and Run :  open the project folder in your code editor and open terminal

2024-01-23 15:41 UTC, DBeniskos commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
So what you suggest to do

2024-01-23 16:49 UTC, SergiiVolodkoWorking commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
I think it makes sense to address Seth's comment, by implementing project structure like:
```
src
|- WebApi\WebApi.csproj
test
|- WebApi.Tests\WebApi.Tests.csproj
```

2024-01-23 17:02 UTC, SergiiVolodkoWorking commented on README.md
> +- in terminal run the following comand :
Those instructions are usually for someone within the team or from outside the team who might see the project for the first time. So the more precise the are, the less likely someone is going to chase you to help with setting up the project. Good way to test the instructions is to clone the project to the new place and execute exactly the described steps. As far as I remember, `dotnet test` and `dotnet run` are sensitive to the location for .csproj file. So, especially with the requested folder structure change, it is important to provide in the instructions correct paths to the projects either as parameters of `dotnet` commands or as navigation steps

2024-01-23 17:03 UTC, SergiiVolodkoWorking commented
Seems like this PR is missing description, could you please add a brief description of what was done?

2024-01-24 08:35 UTC, DBeniskos commented on README.md
> +- in terminal run the following comand :
I updated the instructions

2024-01-24 08:54 UTC, DBeniskos commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
I added the correct names and paths

2024-01-24 13:30 UTC, sethpthomas91 requested changes
Please address the sln issue and the PR description.

2024-01-24 13:30 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebApi.Tests", "test\WebApi.Tests\WebApi.Tests.csproj", "{7F65A87F-C9DF-4E9B-A23A-54254629A232}"
Why did we remove the WebApi from the dotnet sln?

2024-01-24 13:42 UTC, SergiiVolodkoWorking commented on README.md
> +- after that run ```dotnet run --project src/WebApi/``` to run the application
Cool! Will the previous line `dotnet build` also work form the root folder or it also need `--project` parameter?

2024-01-24 13:43 UTC, SergiiVolodkoWorking commented on README.md
> +- in terminal run the following comand :
Cool! So `dotnet test` doesn't need `--project` parameter and just work from the solution's root?

2024-01-24 13:45 UTC, SergiiVolodkoWorking commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "test", "test\test.csproj", "{76D49B7F-268F-4F2D-AF3E-F9D5DF89ACF7}"
Thx, please address Seth's finding, seems like `src/WebApi` project was deleted from the solution and replaced with `Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "test", "test",`

2024-01-24 13:55 UTC, Kterlecki commented on test/WebApi.Tests/WebApi.Tests.cs
> +namespace test;
+1

2024-01-24 14:02 UTC, Kterlecki commented on README.md
> +```your_ubuntu_full_path_here_where_the_project_is_cloned/practice-basic-webapi-application```
As a personal preference I would be consistent with naming styles, If your going to use '_' or '-' I would try to keep it the same throughout, On a side note as per dotnet guides - https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions, use of hyphens or underscores is discouraged.

2024-01-24 14:06 UTC, Kterlecki commented on README.md
> +```your_ubuntu_full_path_here_where_the_project_is_cloned/practice-basic-webapi-application```
same as above

2024-01-24 16:29 UTC, DBeniskos commented on README.md
> +```your_ubuntu_full_path_here_where_the_project_is_cloned/practice-basic-webapi-application```
Thank you for the tip.

2024-01-24 16:29 UTC, DBeniskos commented on test/WebApi.Tests/WebApi.Tests.cs
> +namespace test;
I will, it was a mistake

2024-01-24 16:31 UTC, DBeniskos commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebApi.Tests", "test\WebApi.Tests\WebApi.Tests.csproj", "{7F65A87F-C9DF-4E9B-A23A-54254629A232}"
It was a mistake, i have to added again because i changed the source file names

2024-01-24 17:08 UTC, sethpthomas91 requested changes
Almost there! Please address the sln issue.

2024-01-24 17:08 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebApi.Tests", "test\WebApi.Tests\WebApi.Tests.csproj", "{7F65A87F-C9DF-4E9B-A23A-54254629A232}"
Ok. Let's fix it here with the ```dotnet sln remove``` command or by deleting it.

2024-01-25 09:36 UTC, DBeniskos commented on README.md
> +- after that run ```dotnet run --project src/WebApi/``` to run the application
So i updated the instructions added in  'dotnet build' the parameter '--project' in order to build for the specific folder.
If user runs dotnet build it will work too but it will build both the source and the test, so i added the parameters in order build and run separately

2024-01-25 09:43 UTC, DBeniskos commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebApi.Tests", "test\WebApi.Tests\WebApi.Tests.csproj", "{7F65A87F-C9DF-4E9B-A23A-54254629A232}"
If i removed this test from the solution, then the testing stops working.
I think this test declares the folder where the WebApi.Tests is locaded, correct me if I'm wrong.

2024-01-25 10:00 UTC, SergiiVolodkoWorking commented on README.md
> +- after that run ```dotnet run --project src/WebApi/``` to run the application
Good point! Indeed, if `dotnet build` builds both projects, it is okay to leave it as you had before, just mentioning in the instruction that it will build all projects in the solution

2024-01-25 10:05 UTC, SergiiVolodkoWorking commented on PracticeWebApi.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebApi.Tests", "test\WebApi.Tests\WebApi.Tests.csproj", "{7F65A87F-C9DF-4E9B-A23A-54254629A232}"
C# solutions are quite fragile and it is a good exercise to get hands on fixing them. The issue is definitely solvable in clean way. There must be an error in the setup or test run instructions. Please have another look. Will be happy to pair if you're stuck.

2024-01-25 13:16 UTC, sethpthomas91 requested changes
Very close to cleaning this up. All changes to fix this are going to be in the PracticeWebApi.sln. Take a look at line 6-7 and line 10-11. These are not csproj directories anymore since you removed them. What you need to do is see if those are referenced anywhere else in this file. Check out the bottom of the file, in GlobalSection(NestedProjects).  In order to get this to work I had to remove some lines just from this sln file. The console commands were not working.

Just for context we have a ton of developer teams that are moving to dotnet 6 and 8 from dotnet 4.8.1. Having the ability to troubleshoot this type of issue is going to be key to helping those teams out. Especially with training them in best practices. A ton also use notepad++, so lack the ability to have an fancy IDE to take care of this.

Let me know if you can't get this compiling after hunting down this issue and we'll pair on it!

2024-01-25 15:26 UTC, sethpthomas91 requested changes
Delete these lines and it should work

2024-01-25 15:26 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +EndProject
```suggestion
```

2024-01-25 15:26 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +EndProject
```suggestion
```

2024-01-25 15:26 UTC, sethpthomas91 commented on PracticeWebApi.sln
>  	EndGlobalSection
```suggestion
```

2024-01-25 17:42 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +		{46C05596-F99B-41BC-ADFA-189A2E5C641E}.Release|x86.Build.0 = Release|Any CPU
```suggestion
		{7F65A87F-C9DF-4E9B-A23A-54254629A232}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{7F65A87F-C9DF-4E9B-A23A-54254629A232}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{7F65A87F-C9DF-4E9B-A23A-54254629A232}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{7F65A87F-C9DF-4E9B-A23A-54254629A232}.Release|Any CPU.Build.0 = Release|Any CPU
		{46C05596-F99B-41BC-ADFA-189A2E5C641E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{46C05596-F99B-41BC-ADFA-189A2E5C641E}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{46C05596-F99B-41BC-ADFA-189A2E5C641E}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{46C05596-F99B-41BC-ADFA-189A2E5C641E}.Release|Any CPU.Build.0 = Release|Any CPU
```

2024-01-25 17:43 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +		Debug|x86 = Debug|x86
```suggestion
```

2024-01-25 17:43 UTC, sethpthomas91 commented on PracticeWebApi.sln
> +		Release|x86 = Release|x86
```suggestion
```

2024-01-26 15:11 UTC, sethpthomas91 approved these changes
Great!

2024-01-26 15:18 UTC, merged