#DCE-158 Publish artifact
DBeniskos/practice-basic-webapi-application pull request #7
Opened 2024-01-29 15:45 UTC by DBeniskos

# Basic Pr Template

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This Pr Template ensure that in each pull_request the code remains clean and up_running.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Necessary steps 
- [ ] Updated gitignore (in order the repository to stay clean from unnecessary thinks)
- [ ] Updated Readme file (contains full instructions)
- [ ] Include comments where is needed

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No
- [ ] I need help with writing tests

2024-01-29 16:13 UTC, sethpthomas91 requested changes
Almost there! Please update your PR description when for all PRs.

2024-01-29 16:13 UTC, sethpthomas91 commented on src/WebApi/Readme.txt
Can we try to guide our users a bit more for folks that may not know how to use Github Actions? If you were describing this to a non-dev how would we instruct them to download and use this application?

2024-01-29 16:13 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +            ./publish/README.md
```suggestion
            ./publish/README.md

```

2024-01-29 16:13 UTC, sethpthomas91 commented on .github/workflows/test.yml
>          run: echo "Hello, World"
```suggestion
```
No longer needed.

2024-01-30 13:12 UTC, sethpthomas91 requested changes
Please include a description in your PR description.

2024-01-30 13:13 UTC, sethpthomas91 commented on README.md
> +- open **Readme.txt** file to see intructons about the apllication
```suggestion
- open **Readme.txt** file to see instructions about the application
```

2024-01-30 13:14 UTC, sethpthomas91 requested changes

2024-01-30 13:14 UTC, sethpthomas91 commented on src/WebApi/Readme.txt
Can you look into best practices for READMEs? Should we have this one in a separate file from the main README? Great instructions, but having more than one README can really gunk up updating the README.

2024-02-01 01:25 UTC, sethpthomas91 requested changes
Almost there!

2024-02-01 01:25 UTC, sethpthomas91 commented on .github/workflows/test.yml
> +            ./publish/README.md
Can we put in the CRLF in this file? Just to standardize and lint our ymls?

2024-02-01 01:25 UTC, sethpthomas91 commented on README.md
> +- for stopping the applicion just close the window,
```suggestion
- for stopping the application just close the window, 
```
Do you have a plugin for proofreading the text docs? Just something helpful for your local machine. I make typos all the time too!

2024-02-01 01:25 UTC, sethpthomas91 commented on .github/workflows/test.yml
>          uses: actions/checkout@v3
Can we also use the most up to date version of this action? There is a node js warning in the workflow.

2024-02-01 09:02 UTC, DBeniskos commented on README.md
> +- for stopping the applicion just close the window,
Do you have something to suggest me for windows?

2024-02-01 09:23 UTC, DBeniskos commented on .github/workflows/test.yml
>          uses: actions/checkout@v3
I updated the yml file

2024-02-02 14:28 UTC, sethpthomas91 commented on README.md
> +- for stopping the applicion just close the window,
I do not. Not sure if one of the other folks has anything. I do a ton of dev on my mac. Maybe it would be a good idea to look into a linting service for our CI? It may be overkill though

2024-02-02 15:53 UTC, sethpthomas91 approved these changes

2024-02-02 15:54 UTC, merged